# Generated by Django 4.2 on 2023-04-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirm_password',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.TextField(choices=[('Male', 'Male'), ('Female', 'Female')], default='not_known', max_length=10),
        ),
    ]
