# Generated by Django 4.1.7 on 2023-04-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=255),
        ),
    ]
