# Generated by Django 4.1.7 on 2023-04-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_category_name_alter_comment_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.TextField(max_length=255),
        ),
    ]
