# Generated by Django 4.2 on 2023-04-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
